name: this is new workflow demo

on:
  push:
    branches:
      - main

jobs:
  lambdadeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: check the files
        run: ls -ls
      - name: checking version
        run: aws --version
      - name: checking version
        run: aws --version
      - name: zipping pythn file
        run: zip -r python.zip python.py
        
      