name: this is new workflow demo

on:
  push:
    branches:
      - main

jobs:
  lambdadeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: check the files
        run: ls -ls
      - name: checking version
        run: aws --version
      - name: checking version
        run: aws --version
      - name: zipping pythn file
        run: zip -r python.zip *.py
      - name: lambda code update
        run: aws lambda update-function-code --function-name  git_trigger  --zip-file fileb://python.zip
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEYS}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECREAT_KEYS}}
          AWS_DEFAULT_REGION : "us-east-1"
