name: development

on:
  push:
    branches:
      - main

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: checking
        run: ls -ls
      - name: printing
        run: echo "new file trying" > new1
      - name: opening file
        run: cat new1